[package]
name = "canaryd"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "canaryd"
path = "src/main.rs"

[dependencies]
canary-core.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
clap.workspace = true
thiserror.workspace = true
base64.workspace = true
hex.workspace = true
rand.workspace = true
url.workspace = true
chrono.workspace = true
tokio.workspace = true
tokio-util.workspace = true
axum.workspace = true
reqwest.workspace = true
sqlx.workspace = true
async-trait.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zeroize.workspace = true

[dev-dependencies]
tower.workspace = true
http-body-util.workspace = true
tempfile.workspace = true

[lints]
workspace = true
